# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-di-christian"
    dynamodb_table = "my-student-alias"
    encrypt        = true
    key            = "stage/services/webserver-cluster/terraform.tfstate"
    region         = "us-west-1"
  }
}
