# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-2"

  default_tags {
   tags = {
     CostCenter  = "tf-advanced"
     Project     = "Terraform-Advanced"
   }
 }
}
